notes_dir = "~/Documents/ekphos"
welcome_shown = true
theme = "poimandres"
show_empty_dir = true
syntax_theme = "InspiredGithub"
sidebar_collapsed = false
outline_collapsed = false
folders_first = true
frontmatter_hidden = true
show_tags = true
transparent_bg = true

[editor]
line_wrap = true
tab_width = 4
left_padding = 0
right_padding = 1
line_numbers = "absolute"
scrolloff = 0
